apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schahid-argo-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/chahid001/IoT-test.git
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true